import typer
from typer import Argument

from hand.config import settings
from ..check import DoCheck
from ..opt import Opt


def grant_read_access(
    hw_title: str = Argument(
        default=..., metavar="📝hw", help="target homework to grant access to"
    ),
    dry: bool = Opt.DRY,
    yes: bool = Opt.ACCEPT_ALL,
):
    """Make TAs being able to read all homework repos

    "team-slug": the field auto generated by github.

    For example: the team-slug of "2019 Teaching-team" would be "2019_teaching-team".
    """
    DoCheck(gh_config_valid=True)

    org, team = settings.github.org, settings.grant.reader_team

    if not (
        yes or typer.confirm(f"Grant read access of {org}/{hw_title} to {org}/{team}?")
    ):
        raise typer.Abort()

    # additional checks
    print("check reader team exists")
    print("check have repo with hw")
